// Sets package.json version and src/version.js to the git commit count: 0.0.{N}
// Flags:
//   --next  count + 1  (pre-commit hook: predicts post-commit count)
//   --dry   print only, no write  (check version before writing commit message)
// If git is unavailable (no .git dir, CI shallow env), exits without writing
// so an existing committed version is never clobbered.

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const args = process.argv.slice(2)
const next = args.includes('--next')
const dry = args.includes('--dry')

const pkgPath = path.join(__dirname, '..', 'package.json')
const versionJsPath = path.join(__dirname, '..', 'src', 'version.js')

let count
try {
  count = parseInt(execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim(), 10)
} catch (_) {
  process.stdout.write('sync-version: git unavailable, keeping existing version\n')
  process.exit(0)
}

if (!Number.isInteger(count) || count < 1) {
  process.stdout.write('sync-version: unexpected git output, keeping existing version\n')
  process.exit(0)
}

if (next) count += 1
const version = `0.0.${count}`

if (dry) {
  process.stdout.write(`${version}\n`)
  process.exit(0)
}

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
pkg.version = version
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

// CRA forbids imports from outside src/, so the version is mirrored into a
// generated module that App.js can import.
fs.writeFileSync(versionJsPath, `// Generated by scripts/sync-version.js -- do not edit by hand.
export const APP_VERSION = '${version}';
`)

process.stdout.write(`version → ${version}\n`)
